### ISSUE TITLE
entity 如何发送的？

### ISSUE THREAD

**Issue by linonetwo** [jinleili/bevy-in-web-worker#2]
我翻了一下代码没找到 entity 是如何在两个 bevy 实例之间同步的，能请教一下在哪里吗？

目前的实现似乎是复用代码在主进程和工作进程都启动一个 Bevy 实例，然后根据条件在主进程仅执行渲染系统，在工作进程只执行 AABB 射线碰撞检测系统，是这样吗？

**Comment by jinleili** [comment]
bevy 实例之间没有同步， 两个实例都是独立运行的。做这个示例的目的在 [README](https://github.com/jinleili/bevy-in-web-worker/blob/main/zh.md) 中已经有详细的介绍。

**Comment by linonetwo** [comment]
好吧，那就是只做了鼠标事件的发送。

我主要是想在 tauri rust 里跑 bevy，但在 html 界面上渲染 canvas，所以来参考一下。
